ARG MAJOR_VERSION=latest

FROM quay.io/toolbx-images/opensuse-toolbox:${MAJOR_VERSION}

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used with the toolbox or distrobox command" \
      summary="A cloud-native terminal experience" \
      maintainer="contact@aguslr.com"

COPY extra-packages /

RUN grep -v '^#' /extra-packages | xargs zypper -n install --no-recommends && \
    rm /extra-packages

RUN \
    ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/dconf && \
    ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/distrobox && \
    ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/docker && \
    ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/docker-compose && \
    ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/espeak-ng && \
    ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/flatpak && \
    ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/gnome-session-inhibit && \
    ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/gsettings && \
    ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/journalctl && \
    ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/nautilus && \
    ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/notify-send && \
    ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/ostree && \
    ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/podman && \
    ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/podman-compose && \
    ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree && \
    ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/systemctl && \
    ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/systemd-inhibit && \
    ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/toolbox && \
    ln -sf /usr/bin/flatpak-xdg-email /usr/local/bin/xdg-email && \
    ln -sf /usr/bin/flatpak-xdg-open /usr/local/bin/xdg-open
