name: Build Ubuntu images

on:
  schedule:
    - cron: '20 20 * * *'  # 8:20pm everyday
  pull_request:
    branches:
      - main
    paths:
      - ubuntu/**
      - .github/workflows/ubuntu.yml
  push:
    branches:
      - main
    paths:
      - ubuntu/**
      - .github/workflows/ubuntu.yml
  workflow_dispatch:

env:
  DISTRO: 'ubuntu'
  IMAGE_NAME: 'toolbx-ubuntu'
  REGISTRY_URL: ghcr.io
  REGISTRY_USERNAME: ${{ github.repository_owner }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        major_version: ['20.04', '22.04']
        include:
          - major_version: '20.04'
            is_latest: false
          - major_version: '22.04'
            is_latest: true

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=${{ matrix.major_version }},enable=${{ github.event_name != 'pull_request' && matrix.major_version != '' }}
            type=raw,value=latest,enable=${{ github.event_name != 'pull_request' && matrix.is_latest == true }}
            type=ref,suffix=-${{ matrix.major_version }},event=pr,enable=${{ github.event_name == 'pull_request' }}
            type=schedule,prefix=${{ matrix.major_version }}-,pattern={{date 'YYYYMMDD'}},enable=${{ github.event_name == 'schedule' }}
            type=semver,pattern={{version}}
            type=sha,prefix=sha256-

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          context: |
            ./${{ env.DISTRO }}
          containerfiles: |
            ./${{ env.DISTRO }}/Containerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            MAJOR_VERSION=${{ matrix.major_version }}
          oci: false

      - name: Push to container registries
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          tags: ${{ steps.build_image.outputs.tags }}
          extra-args: |
            --disable-content-trust

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.2

      - name: Sign container image
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}@${TAGS}
        env:
          TAGS: ${{ steps.push.outputs.digest }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_KEY }}
          COSIGN_EXPERIMENTAL: false

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
